# Generated by Django 2.1.4 on 2018-12-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklist',
            name='mod_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
