# Generated by Django 2.1.4 on 2018-12-09 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eToolActivation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(verbose_name='EMP ID')),
                ('emp_name', models.CharField(max_length=20, verbose_name='EMP NAME')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('etool_activation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eToolActivation.eToolActivation')),
                ('supervisor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
