# Generated by Django 2.1.4 on 2018-12-10 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eToolActivation', '0009_remove_etoolactivation_emp_master'),
        ('empMaster', '0002_remove_empmaster_etool_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmaster',
            name='etoolactivation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eTool', to='eToolActivation.eToolActivation'),
            preserve_default=False,
        ),
    ]
