# Generated by Django 2.1.4 on 2018-12-10 20:27

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0009_auto_20170124_1125'),
        ('empMaster', '0004_auto_20181211_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmaster',
            name='status',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State'),
        ),
    ]
