# Generated by Django 2.1.4 on 2018-12-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empMaster', '0005_empmaster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmaster',
            name='etoolactivation',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eTool', to='eToolActivation.eToolActivation'),
        ),
    ]
