# Generated by Django 2.1.4 on 2018-12-17 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('empMaster', '0006_auto_20181211_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmaster',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+918335000105', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empmaster',
            name='cswon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CSWON'),
        ),
        migrations.AddField(
            model_name='empmaster',
            name='emp_designation',
            field=models.CharField(default='UNK', max_length=10, verbose_name='EMP Designation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empmaster',
            name='exp_yrs',
            field=models.IntegerField(default=0, verbose_name='Experience Years'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empmaster',
            name='onboard_date',
            field=models.DateField(blank=True, null=True, verbose_name='Onboard Date'),
        ),
        migrations.AddField(
            model_name='empmaster',
            name='skill_set',
            field=models.CharField(default='UNK', max_length=50, verbose_name='Skill Set'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empmaster',
            name='emp_name',
            field=models.CharField(max_length=20, verbose_name='EMP Name'),
        ),
        migrations.AlterField(
            model_name='empmaster',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
