# Generated by Django 2.1.4 on 2018-12-18 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empMaster', '0007_auto_20181218_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creat_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empmaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empmaster',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Role'),
        ),
    ]
