# Generated by Django 2.1.4 on 2018-12-18 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empMaster', '0008_auto_20181219_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empmaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
