# Generated by Django 2.1.4 on 2018-12-18 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empMaster', '0010_auto_20181219_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmaster',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={models.Q(('role', 'Project Lead'), ('role', 'Account Manager'), _connector='OR')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Role'),
        ),
    ]
