# Generated by Django 2.1.4 on 2018-12-18 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empMaster', '0013_auto_20181219_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmaster',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('primary_role', 'PL'), ('primary_role', 'AM'), ('secondary_role', 'PL'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Role'),
        ),
    ]
