# Generated by Django 2.1.4 on 2018-12-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empMaster', '0014_auto_20181219_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empmaster',
            old_name='emp_designation',
            new_name='emp_desig',
        ),
    ]
