# Generated by Django 2.1.4 on 2018-12-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empMaster', '0015_auto_20181219_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empmaster',
            name='etoolactivation',
        ),
    ]
