# Generated by Django 2.1.4 on 2018-12-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empMaster', '0016_remove_empmaster_etoolactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmaster',
            name='account_manager',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Account Manager'),
        ),
    ]
