# Generated by Django 2.1.4 on 2018-12-23 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0008_role_view_all'),
        ('river', '0009_auto_20170124_1125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adhocTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('task_description', models.TextField(max_length=500, verbose_name='Item Description')),
                ('account_manager', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Account Manager')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('assigned_to', models.ForeignKey(limit_choices_to=models.Q(('primary_role', 'PL'), ('primary_role', 'ETSPOC'), ('secondary_role', 'PL'), ('secondary_role', 'ETSPOC'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='role.Role')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adhoctask_create_by', to=settings.AUTH_USER_MODEL)),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adhoctask_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
