# Generated by Django 2.1.4 on 2019-01-02 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('river', '0010_auto_20190103_0030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adhocTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_subject', models.CharField(max_length=100, verbose_name='Task Subject')),
                ('task_description', models.TextField(max_length=500, verbose_name='Task Description')),
                ('resolution_description_history', models.CharField(blank=True, max_length=600, null=True, verbose_name='Resolution Description History')),
                ('add_resolution_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Add Resolution Description')),
                ('complete_restart_reason_history', models.CharField(blank=True, max_length=600, null=True, verbose_name='Complete/Restart Comments History')),
                ('add_complete_restart_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Add Complete/Restart Comments')),
                ('account_manager', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Account Manager')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('assigned_to', models.ForeignKey(limit_choices_to=models.Q(('primary_role', 'PL'), ('primary_role', 'ETSPOC'), ('secondary_role', 'PL'), ('secondary_role', 'ETSPOC'), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, to='role.Role')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adhoctask_create_by', to=settings.AUTH_USER_MODEL)),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adhoctask_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
