# Generated by Django 2.1.4 on 2018-12-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoctask',
            name='resolution_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Resolution Description'),
        ),
        migrations.AddField(
            model_name='adhoctask',
            name='restart_reason',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Restart Reason'),
        ),
        migrations.AlterField(
            model_name='adhoctask',
            name='task_description',
            field=models.TextField(max_length=500, verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='adhoctask',
            name='task_subject',
            field=models.CharField(max_length=100, verbose_name='Task Subject'),
        ),
    ]
