# Generated by Django 2.1.4 on 2018-12-23 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adhocTask', '0002_auto_20181224_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhoctask',
            name='restart_reason',
        ),
        migrations.AddField(
            model_name='adhoctask',
            name='complete_restart_reason',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Complete/Restart Comments'),
        ),
        migrations.AlterField(
            model_name='adhoctask',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to=models.Q(('primary_role', 'PL'), ('primary_role', 'ETSPOC'), ('secondary_role', 'PL'), ('secondary_role', 'ETSPOC'), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, to='role.Role'),
        ),
    ]
