# Generated by Django 2.1.4 on 2018-12-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='supervisor_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
