# Generated by Django 2.1.4 on 2018-12-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_role_supervisor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
