# Generated by Django 2.1.4 on 2018-12-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_role_supervisor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='primary_role',
        ),
        migrations.AddField(
            model_name='role',
            name='secondary_role',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
