# Generated by Django 2.1.4 on 2018-12-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_auto_20181219_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='primary_role',
            field=models.CharField(blank=True, choices=[('PL', 'Project Lead'), ('AM', 'Account Manager'), ('ETSPOC', 'eTool SPOC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='secondary_role',
            field=models.CharField(blank=True, choices=[('ETSPOC', 'eTool SPOC')], max_length=20),
        ),
    ]
