# Generated by Django 2.1.4 on 2018-12-19 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0005_auto_20181219_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='supervisor_id',
            new_name='supervisor_emp_id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='supervisor_name',
        ),
        migrations.AddField(
            model_name='role',
            name='supervisor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprvsr', to=settings.AUTH_USER_MODEL),
        ),
    ]
