# Generated by Django 2.1.4 on 2018-12-19 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_auto_20181219_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprvsr', to=settings.AUTH_USER_MODEL),
        ),
    ]
