# Generated by Django 2.1.4 on 2018-12-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0007_auto_20181219_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='view_all',
            field=models.BooleanField(default=False, verbose_name='View All Recs?'),
        ),
    ]
