# Generated by Django 2.1.4 on 2018-12-09 08:44

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '0009_auto_20170124_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='eToolActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=uuid.uuid4, editable=False, max_length=50, verbose_name='Item Number')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Item Description')),
                ('team_lead_check_list_1', models.BooleanField(default=False, verbose_name='Team Lead Check List 1')),
                ('team_lead_check_list_2', models.BooleanField(default=False, verbose_name='Team Lead Check List 2')),
                ('team_lead_check_list_3', models.BooleanField(default=False, verbose_name='Team Lead Check List 3')),
                ('team_lead_check_list_4', models.BooleanField(default=False, verbose_name='Team Lead Check List 4')),
                ('team_lead_check_list_5', models.BooleanField(default=False, verbose_name='Team Lead Check List 5')),
                ('spoc_check_list_1', models.BooleanField(default=False, verbose_name='SPOC Check List 1')),
                ('spoc_check_list_2', models.BooleanField(default=False, verbose_name='SPOC Check List 2')),
                ('spoc_check_list_3', models.BooleanField(default=False, verbose_name='SPOC Check List 3')),
                ('spoc_check_list_4', models.BooleanField(default=False, verbose_name='SPOC Check List 4')),
                ('spoc_check_list_5', models.BooleanField(default=False, verbose_name='SPOC Check List 5')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
            ],
        ),
    ]
