# Generated by Django 2.1.4 on 2019-01-02 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('ManpowerManagement', '0001_initial'),
        ('river', '0010_auto_20190103_0030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='eToolActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(verbose_name='EMP ID')),
                ('no', models.CharField(default=uuid.uuid4, editable=False, max_length=50, verbose_name='Item Number')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Item Description')),
                ('team_lead_check_list_1', models.BooleanField(default=False, verbose_name='Team Lead Check List 1')),
                ('team_lead_check_list_2', models.BooleanField(default=False, verbose_name='Team Lead Check List 2')),
                ('team_lead_check_list_3', models.BooleanField(default=False, verbose_name='Team Lead Check List 3')),
                ('team_lead_check_list_4', models.BooleanField(default=False, verbose_name='Team Lead Check List 4')),
                ('team_lead_check_list_5', models.BooleanField(default=False, verbose_name='Team Lead Check List 5')),
                ('team_lead_comments', models.TextField(blank=True, max_length=200, null=True, verbose_name='Team Lead Comments')),
                ('spoc_check_list_1', models.BooleanField(default=False, verbose_name='SPOC Check List 1')),
                ('spoc_check_list_2', models.BooleanField(default=False, verbose_name='SPOC Check List 2')),
                ('spoc_check_list_3', models.BooleanField(default=False, verbose_name='SPOC Check List 3')),
                ('spoc_check_list_4', models.BooleanField(default=False, verbose_name='SPOC Check List 4')),
                ('spoc_check_list_5', models.BooleanField(default=False, verbose_name='SPOC Check List 5')),
                ('spoc_comments', models.TextField(blank=True, max_length=200, null=True, verbose_name='SPOC Comments')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('motion_date', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Motion Date')),
                ('account_manager', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Account Manager')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etool_create_by', to=settings.AUTH_USER_MODEL)),
                ('emp_master', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eTool', to='ManpowerManagement.EmpRegistration')),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to=models.Q(('primary_role', 'PL'), ('primary_role', 'AM'), ('secondary_role', 'PL'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Role')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etool_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
