# Generated by Django 2.1.4 on 2018-12-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eToolActivation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etoolactivation',
            name='motion_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
