# Generated by Django 2.1.4 on 2018-12-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eToolActivation', '0002_etoolactivation_motion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etoolactivation',
            name='motion_date',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Motion Date'),
        ),
    ]
