# Generated by Django 2.1.4 on 2018-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eToolActivation', '0003_auto_20181209_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='etoolactivation',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Completion Date'),
        ),
    ]
