# Generated by Django 2.1.4 on 2018-12-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empMaster', '0002_remove_empmaster_etool_activation'),
        ('eToolActivation', '0004_etoolactivation_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='etoolactivation',
            name='emp_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empMaster.empMaster'),
        ),
    ]
