# Generated by Django 2.1.4 on 2018-12-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eToolActivation', '0005_etoolactivation_emp_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etoolactivation',
            name='completion_date',
        ),
    ]
