# Generated by Django 2.1.4 on 2018-12-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eToolActivation', '0008_auto_20181211_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etoolactivation',
            name='emp_master',
        ),
    ]
