# Generated by Django 2.1.4 on 2018-12-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eToolActivation', '0009_remove_etoolactivation_emp_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='etoolactivation',
            name='emp_id',
            field=models.IntegerField(default=0, editable=False, verbose_name='EMP ID'),
            preserve_default=False,
        ),
    ]
