# Generated by Django 2.1.4 on 2018-12-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empMaster', '0016_remove_empmaster_etoolactivation'),
        ('eToolActivation', '0010_etoolactivation_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='etoolactivation',
            name='emp_master',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eTool', to='empMaster.empMaster'),
        ),
    ]
