# Generated by Django 2.1.4 on 2018-12-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eToolActivation', '0012_auto_20181219_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etoolactivation',
            name='emp_master',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eTool', to='empMaster.empMaster'),
        ),
    ]
