# Generated by Django 2.1.4 on 2018-12-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eToolActivation', '0014_auto_20181220_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etoolactivation',
            name='emp_id',
            field=models.IntegerField(verbose_name='EMP ID'),
        ),
    ]
