# Generated by Django 2.1.4 on 2018-12-11 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('river', '0009_auto_20170124_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOWRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('sow_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SOW Value')),
                ('sow_start_date', models.DateTimeField(verbose_name='SOW Start Date')),
                ('sow_end_date', models.DateTimeField(verbose_name='SOW End Date')),
                ('sow_type', models.CharField(max_length=10, verbose_name='Type')),
                ('remarks', models.TextField(max_length=200, verbose_name='Remarks')),
                ('compliance_team_approval_date', models.DateTimeField(verbose_name='Compliance Team Approval Date')),
                ('tcs_contract_id', models.CharField(max_length=50, verbose_name='TCS Contract ID')),
                ('legal_approval_date', models.DateTimeField(verbose_name='Legal Approval Date')),
                ('pob_approval', models.BooleanField(default=False, verbose_name='POB Approval')),
                ('pob_remarks', models.CharField(max_length=200, verbose_name='POB Remarks')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create', to=settings.AUTH_USER_MODEL)),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
            ],
        ),
        migrations.CreateModel(
            name='WonCreationExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcs_contract_id', models.CharField(max_length=50, verbose_name='TCS Contract ID')),
                ('won', models.CharField(blank=True, max_length=10, null=True, verbose_name='WON')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
            ],
        ),
        migrations.AddField(
            model_name='sowregistration',
            name='woncreationextension',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='woncrtext', to='SOWRegistration.WonCreationExtension'),
        ),
    ]
