# Generated by Django 2.1.4 on 2019-01-02 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('river', '0010_auto_20190103_0030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOWRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('amendment_no', models.PositiveSmallIntegerField(default=0, verbose_name='Amendment Number')),
                ('sow_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SOW Value')),
                ('sow_start_date', models.DateField(verbose_name='SOW Start Date')),
                ('sow_end_date', models.DateField(verbose_name='SOW End Date')),
                ('amendment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amendment Value')),
                ('amendment_start_date', models.DateField(blank=True, null=True, verbose_name='Amendment Start Date')),
                ('amendment_end_date', models.DateField(blank=True, null=True, verbose_name='Amendment End Date')),
                ('sow_type', models.CharField(max_length=10, verbose_name='Type')),
                ('remarks', models.TextField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('compliance_team_approval_date', models.DateField(blank=True, null=True, verbose_name='Compliance Team Approval Date')),
                ('tcs_contract_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='TCS Contract ID')),
                ('legal_approval_date', models.DateField(blank=True, null=True, verbose_name='Legal Approval Date')),
                ('pob_approval', models.BooleanField(default=False, verbose_name='POB Approval')),
                ('pob_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='POB Remarks')),
                ('crt_upd_won_sow', models.BooleanField(default=False, verbose_name='Create/Update WONs for SOW ID')),
                ('account_manager', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Account Manager')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sowreg_create_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, limit_choices_to=models.Q(primary_role='AM'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='role.Role')),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sowreg_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WonCreationExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.CharField(blank=True, max_length=10, null=True, verbose_name='WON')),
                ('milestone', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Milestone')),
                ('milestone_date', models.DateField(blank=True, null=True, verbose_name='Milestone Date')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
                ('account_manager', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Account Manager')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='won_create_by', to=settings.AUTH_USER_MODEL)),
                ('sow_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sowregn', to='SOWRegistration.SOWRegistration')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='won_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
