# Generated by Django 2.1.4 on 2018-12-11 19:54

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SOWRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowregistration',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sowregistration',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified Date'),
        ),
        migrations.AddField(
            model_name='woncreationextension',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 11, 19, 54, 26, 542786, tzinfo=utc), verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='woncreationextension',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified Date'),
        ),
    ]
