# Generated by Django 2.1.4 on 2018-12-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOWRegistration', '0002_auto_20181214_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowregistration',
            name='amendment_end_date',
            field=models.DateField(default=None, verbose_name='Amendment End Date'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='amendment_start_date',
            field=models.DateField(default=None, verbose_name='Amendment Start Date'),
        ),
    ]
