# Generated by Django 2.1.4 on 2018-12-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOWRegistration', '0002_auto_20181212_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowregistration',
            name='compliance_team_approval_date',
            field=models.DateField(verbose_name='Compliance Team Approval Date'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='legal_approval_date',
            field=models.DateField(verbose_name='Legal Approval Date'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='sow_end_date',
            field=models.DateField(verbose_name='SOW End Date'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='sow_start_date',
            field=models.DateField(verbose_name='SOW Start Date'),
        ),
        migrations.AlterField(
            model_name='woncreationextension',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='woncreationextension',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
