# Generated by Django 2.1.4 on 2018-12-11 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOWRegistration', '0003_auto_20181212_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowregistration',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='sowregistration',
            name='won',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='WON'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='compliance_team_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Compliance Team Approval Date'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='legal_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Legal Approval Date'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='pob_remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='POB Remarks'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='tcs_contract_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TCS Contract ID'),
        ),
        migrations.AlterField(
            model_name='woncreationextension',
            name='tcs_contract_id',
            field=models.CharField(editable=False, max_length=50, verbose_name='TCS Contract ID'),
        ),
        migrations.AlterField(
            model_name='woncreationextension',
            name='won',
            field=models.CharField(editable=False, max_length=10, verbose_name='WON'),
        ),
    ]
