# Generated by Django 2.1.4 on 2018-12-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOWRegistration', '0003_auto_20181214_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowregistration',
            name='amendment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Amendment End Date'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='amendment_no',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Amendment Number'),
        ),
        migrations.AlterField(
            model_name='sowregistration',
            name='amendment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Amendment Start Date'),
        ),
    ]
