# Generated by Django 2.1.4 on 2018-12-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOWRegistration', '0004_auto_20181218_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowregistration',
            name='amendment_no',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Amendment Number'),
        ),
    ]
