# Generated by Django 2.1.4 on 2018-12-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOWRegistration', '0007_auto_20181221_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowregistration',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(primary_role='AM'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='role.Role'),
        ),
        migrations.AlterField(
            model_name='woncreationextension',
            name='sow_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sowregn', to='SOWRegistration.SOWRegistration'),
        ),
    ]
