# Generated by Django 2.1.4 on 2019-01-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManpowerManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregistration',
            name='approver_comments_history',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Record Approver Comments History'),
        ),
        migrations.AlterField(
            model_name='empregistration',
            name='creator_comments_history',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Record Creator Comments History'),
        ),
    ]
